version = 0.1

[default.deploy.parameters]
stack_name = "serverless-api-staging"
resolve_s3 = true
s3_prefix = "serverless-api-staging"
region = "il-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
